# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-lts-latest
  tools:
    nodejs: latest
    # You can also specify other tool versions:
  # <https://vitepress-and-readthedocs-example.readthedocs.io/en/latest/how-to.html>
  commands:
    - mkdir --parents $READTHEDOCS_OUTPUT/html/
    - npm i --verbose
    - patch -i .vocs/1.0.0-alpha.55.diff -p1
    - npx vocs build # -- --base "/$READTHEDOCS_LANGUAGE/$READTHEDOCS_VERSION/"
    - cp --recursive docs/dist/. $READTHEDOCS_OUTPUT/html/ # To include dot hidden file

# Build documentation in the docs/ directory with Sphinx
# sphinx:
#    configuration: docs/conf.py

# If using Sphinx, optionally build your docs in additional formats such as PDF
# formats:
#    - htmlzip
#    - pdf
#    - epub

# Optionally declare the Python requirements required to build your docs
# python:
#    install:
#    - requirements: requirements.txt

